FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm i -g pnpm
RUN pnpm i

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 6969

# Set environment variables
ENV NODE_ENV=development
ENV HOST=0.0.0.0
ENV PORT_HEADER=x-forwarded-port
ENV PORT=6969
ENV ORIGIN=http://localhost:6969

# Start the application
CMD ["pnpm", "dev"]