# docker-compose.yml

services:
  postgres:
    container_name: einkoof-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=einkoof
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5431
    image: postgres:latest
    ports:
      - 5431:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  frontend:
    container_name: einkoof-frontend
    env_file:
      - .env
    ports:
      - 3000:3000
    # The name of the image that will be created when building this container
    build:
      context: .
      dockerfile: Dockerfile
